services:
  backend:
    container_name: triang_infos_api
    build:
      dockerfile: Dockerfile.dev
      context: ./src/backend/
    image: triang_infos_api:latest
    command: "uvicorn api.app:app --reload --host 0.0.0.0"
    volumes:
      - ./src/backend:/opt/app/
    restart: 'no'
    stdin_open: true   # Add this line into your service
    tty: true   # Add this line into your service
    # env_file:
    #   - backend/.env
    environment:
      - PYTHONBREAKPOINT=ipdb.set_trace
      - TRIANG_INFOS_API_CORS=http://localhost:3000
    ports:
      - 8000:8000

  frontend:
    container_name: triang_infos_frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./src/frontend/
    image: triang_infos_frontend:latest
    command: "npm run dev"
    volumes:
      - ./src/frontend/src:/opt/app/src
      - ./src/frontend/public:/opt/app/public
    restart: 'no'
    stdin_open: true   # Add this line into your service
    tty: true   # Add this line into your service
    ports:
      - 3000:3000
