FROM python:3.12.0-slim-bullseye

ENV PYTHONUNBUFFERED=1\
    PYTHONDONTWRITEBYTECODE=1\
    POETRY_VIRTUALENVS_CREATE=false\
    PIP_NO_CACHE_DIR=off

WORKDIR /opt/app

RUN pip install --upgrade pip && pip install poetry

COPY pyproject.toml .
COPY poetry.lock .

RUN poetry install

EXPOSE 8000
